name: neelkanth
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  injectable: 2.3.2
  get_it:
  flutter_riverpod: 2.4.5

  hive: 2.2.3
  hive_flutter: 1.1.0
  easy_localization: 3.0.3
  flutter_screenutil: 5.9.0
  responsive_builder: 0.7.0
  flutter_svg: 2.0.9
  cached_network_image: 3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_carousel_widget: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:
  injectable_generator:
  flutter_native_image:


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - lang/en.json
  fonts:
    - family: TTRationalist
      fonts:
        - asset: assets/fonts/TTRationalist-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Grover
      fonts:
        - asset: assets/fonts/Grover-W01-regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf

