/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  static const String svgBackArrow = "assets/svg/svg_back_arrow.svg";
  static const String svgClose = "assets/svg/svg_close.svg";
  static const String svgDrawerMenu = "assets/svg/svg_drawer_menu.svg";
  static const String svgSuccess = "assets/svg/svg_success.svg";

  static const String bacKLogoSvg = "assets/svg/NE-logo-background-less.svg";

  static const String homeBg = "assets/images/high-angle-asian-food-ingredients-with-copy-space.jpg";


  static const String svgCategoryPlaceHolder = "assets/svg/svg_category_placeholder.svg";

  //
  // static const String ttrationalistBlack = "assets/fonts/TTRationalist-Black.ttf";
  // static const String ttrationalistBlackitalic = "assets/fonts/TTRationalist-BlackItalic.ttf";
  // static const String ttrationalistBold = "assets/fonts/TTRationalist-Bold.ttf";
  // static const String ttrationalistBolditalic = "assets/fonts/TTRationalist-BoldItalic.ttf";
  // static const String ttrationalistDbold = "assets/fonts/TTRationalist-DBold.ttf";
  // static const String ttrationalistDbolditalic = "assets/fonts/TTRationalist-DBoldItalic.ttf";
  // static const String ttrationalistItalic = "assets/fonts/TTRationalist-Italic.ttf";
  // static const String ttrationalistLight = "assets/fonts/TTRationalist-Light.ttf";
  // static const String ttrationalistLightitalic = "assets/fonts/TTRationalist-LightItalic.ttf";
  // static const String ttrationalistMedium = "assets/fonts/TTRationalist-Medium.ttf";
  // static const String ttrationalistMediumitalic = "assets/fonts/TTRationalist-MediumItalic.ttf";
  // static const String ttrationalistNormal = "assets/fonts/TTRationalist-Normal.ttf";
  // static const String ttrationalistNormalitalic = "assets/fonts/TTRationalist-NormalItalic.ttf";
  // static const String ttrationalistRegular = "assets/fonts/TTRationalist-Regular.ttf";
  // static const String ttrationalistThin = "assets/fonts/TTRationalist-Thin.ttf";
  // static const String ttrationalistThinitalic = "assets/fonts/TTRationalist-ThinItalic.ttf";
  // static const String ttrationalistvariableitalic = "assets/fonts/TTRationalistVariableItalic.ttf";
  // static const String ttrationalistvariableroman = "assets/fonts/TTRationalistVariableRoman.ttf";
  // static const String ttrationalistXbold = "assets/fonts/TTRationalist-XBold.ttf";
  // static const String ttrationalistXbolditalic = "assets/fonts/TTRationalist-XBoldItalic.ttf";
  // static const String ttrationalistXlight = "assets/fonts/TTRationalist-XLight.ttf";
  // static const String ttrationalistXlightitalic = "assets/fonts/TTRationalist-XLightItalic.ttf";
  // static const String groverW01Regular = "assets/fonts/Grover-W01-regular.ttf";
  //
  //
  //
}
